import 'dart:io';

import 'package:path/path.dart' as p;

/// The corpus of apps every compiler is proven on (docs/CORPUS.md). Each one
/// is a directory under `corpus/` overlaid onto a fresh `flutter create`
/// app, except [apiSamplesApp] (generated from the Flutter checkout) and
/// [defaultApp] (the plain `flutter create` app the release manifests name).
const corpusApps = [defaultApp, apiSamplesApp, 'stress', 'pub_heavy'];

/// Project name of the default app. It must stay `ref_app`: the package name
/// is part of the kernel (library URIs), and the release manifests record
/// the App sha256 of exactly this app.
const defaultApp = 'ref_app';

/// The app built from Flutter's `examples/api` samples.
const apiSamplesApp = 'api_samples';

final _mainDeclaration = RegExp(
  r'^(?:void|Future<void>)\s+main\s*\(\s*\)',
  multiLine: true,
);

/// Sample libraries (posix paths relative to [lib]) of Flutter's
/// `examples/api/lib` that declare a top-level `main()`, sorted.
List<String> findSampleLibraries(Directory lib) {
  final result = <String>[];
  for (final entity in lib.listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (!_mainDeclaration.hasMatch(entity.readAsStringSync())) continue;
    result.add(
      p.posix.joinAll(p.split(p.relative(entity.path, from: lib.path))),
    );
  }
  return result..sort();
}

/// The `lib/main.dart` of [apiSamplesApp]: imports every sample library
/// (copied to `lib/samples/`) with a prefix and keeps all of their `main`
/// functions reachable, so tree shaking keeps every sample in the snapshot.
/// Which sample runs is decided at run time, so nothing can be folded away.
String renderSamplesEntrypoint(List<String> libraries) {
  if (libraries.isEmpty) throw ArgumentError('no sample libraries');
  final b = StringBuffer()
    ..writeln('// GENERATED by xcross_gen_snapshot:corpus. Do not edit.')
    ..writeln('//')
    ..writeln('// Every Flutter API sample (${libraries.length} libraries),')
    ..writeln('// kept alive through its main function.')
    ..writeln()
    ..writeln("import 'dart:ui' show PlatformDispatcher;")
    ..writeln();
  for (var i = 0; i < libraries.length; i++) {
    b.writeln("import 'samples/${libraries[i]}' as s$i;");
  }
  b
    ..writeln()
    ..writeln('const sampleNames = <String>[');
  for (final library in libraries) {
    b.writeln("  '$library',");
  }
  b
    ..writeln('];')
    ..writeln()
    ..writeln('final sampleMains = <void Function()>[');
  for (var i = 0; i < libraries.length; i++) {
    b.writeln('  s$i.main,');
  }
  b
    ..writeln('];')
    ..writeln()
    ..writeln('void main() {')
    ..writeln('  final route = PlatformDispatcher.instance.defaultRouteName;')
    ..writeln(
      '  var index = sampleNames.indexOf(route.replaceFirst(\'/\', \'\'));',
    )
    ..writeln('  if (index < 0) index = route.length % sampleMains.length;')
    ..writeln('  sampleMains[index]();')
    ..writeln('}');
  return b.toString();
}

/// Copies the sample libraries of [samplesLib] (Flutter's
/// `examples/api/lib`) into `<app>/lib/samples/` and writes the generated
/// `<app>/lib/main.dart`. Returns the number of sample libraries.
int writeSamplesApp({required Directory samplesLib, required Directory app}) {
  final libraries = findSampleLibraries(samplesLib);
  final lib = Directory(p.join(app.path, 'lib'));
  if (lib.existsSync()) lib.deleteSync(recursive: true);
  for (final library in libraries) {
    final target = File(
      p.join(lib.path, 'samples', p.joinAll(library.split('/'))),
    )..parent.createSync(recursive: true);
    File(
      p.join(samplesLib.path, p.joinAll(library.split('/'))),
    ).copySync(target.path);
  }
  File(
    p.join(lib.path, 'main.dart'),
  ).writeAsStringSync(renderSamplesEntrypoint(libraries));
  return libraries.length;
}

/// Generated part of the stress app (`corpus/stress/lib/generated.dart`):
/// wide class hierarchies with many selectors of equal popularity (ties in
/// the dispatch table and selector sorts), big const maps/sets/lists and
/// lots of double/string constants. Deterministic in [classes].
String renderStressGenerated({int classes = 240, int tableSize = 1500}) {
  final b = StringBuffer()
    ..writeln(
      '// GENERATED by `dart run xcross_gen_snapshot:corpus --stress-generated`.',
    )
    ..writeln('// Do not edit; test/corpus_test.dart checks it is up to date.')
    ..writeln()
    ..writeln('// ignore_for_file: type=lint')
    ..writeln();
  // Deterministic pseudo random numbers (LCG), independent of the Dart
  // version running the generator.
  var seed = 0x2545F491;
  int next(int max) {
    seed = (seed * 1103515245 + 12345) & 0x7fffffff;
    return seed % max;
  }

  const interfaces = 12;
  b.writeln('abstract interface class Shape {');
  b.writeln('  int area(int scale);');
  b.writeln('  String describe();');
  b.writeln('}');
  b.writeln();
  for (var i = 0; i < interfaces; i++) {
    b.writeln('abstract interface class Trait$i {');
    b.writeln('  int trait$i(int x);');
    b.writeln('  double weight$i(double x);');
    b.writeln('}');
    b.writeln();
  }
  b.writeln('abstract base class Node implements Shape {');
  b.writeln('  const Node(this.id);');
  b.writeln('  final int id;');
  b.writeln('  @override');
  b.writeln("  String describe() => '\${runtimeType}#\$id';");
  b.writeln('  int visit(int depth) => depth + id;');
  b.writeln('}');
  b.writeln();
  for (var c = 0; c < classes; c++) {
    final traits = <int>{
      for (var k = 0; k < 1 + next(4); k++) next(interfaces),
    }.toList()..sort();
    // Same library, so `final` classes can still be extended here.
    final parent = c < 8 ? 'Node' : 'C${next(c)}';
    final modifier = c < 8 || next(3) != 0 ? 'base' : 'final';
    b.write('$modifier class C$c extends $parent');
    if (traits.isNotEmpty) {
      b.write(' implements ${traits.map((t) => 'Trait$t').join(', ')}');
    }
    b.writeln(' {');
    b.writeln('  const C$c(super.id);');
    b.writeln('  @override');
    b.writeln('  int area(int scale) => scale * ${next(1000) + 1} + id;');
    if (next(2) == 0) {
      b.writeln('  @override');
      b.writeln(
        '  int visit(int depth) => super.visit(depth) ^ ${next(65536)};',
      );
    }
    for (final t in traits) {
      b.writeln('  @override');
      b.writeln('  int trait$t(int x) => x * ${next(97) + 1} - ${next(1000)};');
      b.writeln('  @override');
      b.writeln(
        '  double weight$t(double x) => x * ${_double(next)} + ${_double(next)};',
      );
    }
    b.writeln('}');
    b.writeln();
  }
  b.writeln('const shapes = <Node>[');
  for (var c = 0; c < classes; c++) {
    b.writeln('  C$c($c),');
  }
  b.writeln('];');
  b.writeln();
  b.writeln('int traitSum(Object o, int x) {');
  b.writeln('  var sum = 0;');
  for (var i = 0; i < interfaces; i++) {
    b.writeln(
      '  if (o is Trait$i) sum += o.trait$i(x) + o.weight$i(x / 3).round();',
    );
  }
  b.writeln('  return sum;');
  b.writeln('}');
  b.writeln();
  b.writeln('const wordTable = <String, int>{');
  for (var i = 0; i < tableSize; i++) {
    b.writeln("  '${_word(next)}_$i': ${next(1 << 30)},");
  }
  b.writeln('};');
  b.writeln();
  b.writeln('const doubleTable = <double>[');
  for (var i = 0; i < tableSize; i++) {
    b.writeln('  ${_double(next)},');
  }
  b.writeln('];');
  b.writeln();
  b.writeln('const intSet = <int>{');
  for (var i = 0; i < tableSize; i++) {
    b.writeln('  ${i * 7919 + next(7919)},');
  }
  b.writeln('};');
  b.writeln();
  b.writeln('const recordTable = <(String, int, {double w})>[');
  for (var i = 0; i < tableSize ~/ 3; i++) {
    b.writeln("  ('${_word(next)}', ${next(100000)}, w: ${_double(next)}),");
  }
  b.writeln('];');
  b.writeln();
  b.writeln('const nested = <String, Map<int, List<String>>>{');
  for (var i = 0; i < 60; i++) {
    b.writeln("  'k$i': {");
    for (var j = 0; j < 5; j++) {
      b.writeln(
        "    ${next(1000) * 10 + j}: ['${_word(next)}', '${_word(next)}'],",
      );
    }
    b.writeln('  },');
  }
  b.writeln('};');
  return b.toString();
}

String _word(int Function(int) next) {
  const letters = 'abcdefghijklmnopqrstuvwxyz';
  final n = 3 + next(8);
  return String.fromCharCodes([
    for (var i = 0; i < n; i++) letters.codeUnitAt(next(26)),
  ]);
}

String _double(int Function(int) next) {
  final mantissa = next(1000000);
  final exponent = next(13) - 6;
  return '${mantissa}e$exponent'.replaceFirst('e0', '.0');
}
